my_dbt:
  target: dev
  outputs:
    dev:
      type: mysql
      server: host.docker.internal    #localhost --loacal vs docker
      port: 3306
      user: root
      password: admin
      sdatabase: analytics
      schema: analytics
      connect_timeout: 10
