my_dbt:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      user: root
      password: admin
      sdatabase: analytics
      schema: analytics
      connect_timeout: 10
